import{RULES,damage}from'./combat.js';
const c=document.querySelector('canvas'),x=c.getContext('2d'),keys=new Set(),m={x:640,y:360,a:0,r:0},bg=new Image(),hero=new Image();bg.src='assets/environment/ruined-clearing.png';hero.src='assets/characters/hero-fry-cc0.png';let run=0,last=0,msg='';
const p={x:250,y:360,hp:100,maxHp:100,stamina:100,maxStamina:100,state:'idle',t:0,face:0,hit:0};const e={x:930,y:360,hp:150,maxHp:150,state:'idle',t:0,face:3.14,hit:0,cd:1};
addEventListener('keydown',q=>{keys.add(q.code);if(q.code==='Space')m.a=1;if(q.code.startsWith('Shift'))m.r=1;if(q.code==='KeyR')reset()});addEventListener('keyup',q=>keys.delete(q.code));c.onmousemove=q=>{let b=c.getBoundingClientRect();m.x=(q.clientX-b.left)*1280/b.width;m.y=(q.clientY-b.top)*720/b.height};c.onmousedown=q=>q.button?m.r=1:m.a=1;c.oncontextmenu=q=>q.preventDefault();document.querySelector('button').onclick=()=>{document.querySelector('section').classList.add('hidden');run=1;last=performance.now();requestAnimationFrame(loop)};
const dist=()=>Math.hypot(p.x-e.x,p.y-e.y),norm=(a,b)=>{let l=Math.hypot(a,b)||1;return[a/l,b/l]};
function reset(){Object.assign(p,{x:250,y:360,hp:100,stamina:100,state:'idle',t:0});Object.assign(e,{x:930,y:360,hp:150,state:'idle',t:0,cd:1});msg='守墓人正在注视你'}
function update(dt){p.face=Math.atan2(m.y-p.y,m.x-p.x);p.t+=dt;if(p.state==='roll'){p.x+=Math.cos(p.face)*520*dt;p.y+=Math.sin(p.face)*520*dt;if(p.t>.18)p.state='idle'}else if(p.state==='attack'){if(!p.hit&&p.t>.06&&p.t<.18&&dist()<105){damage(e,RULES.attackDamage);p.hit=1}if(p.t>.24){p.state='idle';if(m.a)Object.assign(p,{state:'attack',t:0,hit:0})}}else{let[a,b]=norm((keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0),(keys.has('KeyS')?1:0)-(keys.has('KeyW')?1:0));p.x+=a*210*dt;p.y+=b*210*dt;if(m.r)Object.assign(p,{state:'roll',t:0});else if(m.a)Object.assign(p,{state:'attack',t:0,hit:0})}m.a=m.r=0;p.x=Math.max(80,Math.min(1200,p.x));p.y=Math.max(70,Math.min(650,p.y));if(e.hp<=0){e.state='dead';msg='遗迹已清理 · R 再战';return}e.face=Math.atan2(p.y-e.y,p.x-e.x);e.cd-=dt;e.t+=dt;if(e.state==='attack'){if(!e.hit&&e.t>.38&&e.t<.54&&dist()<105){damage(p,RULES.enemyDamage,p.state==='roll'||p.state==='hurt');e.hit=1;if(p.hp>0)Object.assign(p,{state:'hurt',t:0})}if(e.t>.7)Object.assign(e,{state:'idle',t:0,cd:.7})}else if(dist()<650){if(dist()<92&&e.cd<0)Object.assign(e,{state:'attack',t:0,hit:0});else{let[a,b]=norm(p.x-e.x,p.y-e.y);e.x+=a*95*dt;e.y+=b*95*dt}}if(p.state==='hurt'&&p.t>.35)p.state='idle';if(p.hp<=0)msg='冒险失败 · 按 R 重试'}
function bar(a,b,w,v,max,col){x.fillStyle='#090909';x.fillRect(a,b,w,16);x.fillStyle=col;x.fillRect(a+2,b+2,(w-4)*v/max,12)}function actor(o,col,r){x.save();x.translate(o.x,o.y);if(o===p&&hero.complete){let frame=Math.floor(performance.now()/180)%4;x.drawImage(hero,frame*40,0,40,64,-26,-45,52,83);if(o.state==='attack'){x.rotate(o.face);x.fillStyle='#f2e6c7';x.fillRect(10,-3,46,6)}x.restore();return}x.rotate(o.face+(o.state==='attack'?o.t*3-1:0));x.fillStyle=col;x.beginPath();x.arc(0,0,r,0,7);x.fill();x.fillStyle='#ddd';x.fillRect(r,-3,40,6);x.restore()}
function draw(){if(bg.complete)x.drawImage(bg,0,0,1280,720);else{x.fillStyle='#17201c';x.fillRect(0,0,1280,720)}x.fillStyle='#08100a55';x.fillRect(0,0,1280,720);if(e.state!=='dead')actor(e,e.state==='attack'&&e.t<.38?'#e0a452':'#8f3632',28);if(p.hp)actor(p,p.state==='hurt'?'#e0d0bd':p.state==='roll'?'#b9e7dc':'#4e9d8c',19);bar(35,35,300,p.hp,100,'#b13d3a');if(e.hp>0){bar(370,665,540,e.hp,150,'#9f3632');x.textAlign='center';x.fillStyle='#eee';x.fillText('遗迹守卫',640,650)}x.font='24px Georgia';x.textAlign='center';x.fillStyle='#f0dfbd';x.fillText(msg,640,110)}function loop(n){let dt=Math.min((n-last)/1000,.033);last=n;if(p.hp&&e.hp)update(dt);draw();requestAnimationFrame(loop)}bg.onload=draw;reset();draw();
