import { RULES, damage } from './combat.js?v=6';
import { sfx, unlockAudio } from './audio.js?v=6';

const canvas=document.querySelector('#game'),ctx=canvas.getContext('2d'),keys=new Set();
const input={x:640,y:360,attack:false,dash:false};
const load=src=>{const image=new Image();image.src=src;return image};
const art={hero:load('assets/characters/warrior-blue.png'),orc:load('assets/characters/orc-soldier-red.png'),grunt:load('assets/characters/orc-grunt.png'),dirt:load('assets/environment/puny/Dirt.png'),grass:load('assets/environment/puny/Grass1.png'),tree:load('assets/environment/puny/Tree.png')};
const player={x:640,y:360,hp:100,maxHp:100,state:'idle',time:0,facing:0,hit:new Set(),moving:false,gold:0};
let enemies=[],drops=[],particles=[],wave=0,nextWave=0,message='',running=false,last=0;
const distance=(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),normal=(x,y)=>{const length=Math.hypot(x,y)||1;return{x:x/length,y:y/length}};

addEventListener('keydown',event=>{keys.add(event.code);if(event.code==='Space')input.attack=true;if(event.code.startsWith('Shift'))input.dash=true;if(event.code==='KeyR')reset()});
addEventListener('keyup',event=>keys.delete(event.code));
canvas.addEventListener('mousemove',event=>{const rect=canvas.getBoundingClientRect();input.x=(event.clientX-rect.left)*1280/rect.width;input.y=(event.clientY-rect.top)*720/rect.height});
canvas.addEventListener('mousedown',event=>event.button?input.dash=true:input.attack=true);canvas.addEventListener('contextmenu',event=>event.preventDefault());
document.querySelector('button').onclick=()=>{unlockAudio();document.querySelector('section').classList.add('hidden');running=true;last=performance.now();requestAnimationFrame(loop)};

function spawnWave(){wave++;const count=Math.min(2+wave,8);for(let i=0;i<count;i++){const angle=i/count*Math.PI*2+wave*.4,radius=240+Math.random()*130;enemies.push({id:`${wave}-${i}`,x:640+Math.cos(angle)*radius,y:360+Math.sin(angle)*radius,hp:70+wave*8,maxHp:70+wave*8,state:'idle',time:0,cooldown:.4+Math.random(),facing:0,moving:false,hit:false,art:i%3?'orc':'grunt'})}message=`第 ${wave} 波 · ${count} 只怪物`;}
function reset(){Object.assign(player,{x:640,y:360,hp:100,state:'idle',time:0,gold:0,hit:new Set()});enemies=[];drops=[];particles=[];wave=0;nextWave=.5;message='准备战斗';}
function burst(x,y,type,count=12){const color=type==='coin'?'#ffd35a':'#65e889';for(let i=0;i<count;i++){const angle=Math.random()*Math.PI*2,speed=60+Math.random()*170;particles.push({x,y,vx:Math.cos(angle)*speed,vy:Math.sin(angle)*speed-80,life:.45+Math.random()*.45,color,size:2+Math.random()*4})}}
function kill(enemy){const index=enemies.indexOf(enemy);if(index<0)return;enemies.splice(index,1);drops.push({x:enemy.x,y:enemy.y,type:'coin',amount:5+Math.floor(Math.random()*8),time:0});burst(enemy.x,enemy.y,'coin',16);if(Math.random()<.38){drops.push({x:enemy.x+25,y:enemy.y,type:'heal',amount:25,time:0});burst(enemy.x+25,enemy.y,'heal',12)}sfx.drop();}

function updatePlayer(dt){player.facing=Math.atan2(input.y-player.y,input.x-player.x);player.time+=dt;player.moving=false;if(player.state==='dash'){player.x+=Math.cos(player.facing)*520*dt;player.y+=Math.sin(player.facing)*520*dt;if(player.time>.18)player.state='idle'}else if(player.state==='attack'){for(const enemy of enemies){if(player.hit.has(enemy.id)||distance(player,enemy)>105)continue;const angle=Math.atan2(enemy.y-player.y,enemy.x-player.x);if(Math.cos(angle-player.facing)>.15&&player.time>.06&&player.time<.19){damage(enemy,RULES.attackDamage);player.hit.add(enemy.id);sfx.hit();if(enemy.hp<=0)kill(enemy)}}if(player.time>.24){player.state='idle';if(input.attack)startAttack()}}else if(player.state==='hurt'){if(player.time>.32)player.state='idle'}else{const direction=normal((keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0),(keys.has('KeyS')?1:0)-(keys.has('KeyW')?1:0));player.moving=!!(direction.x||direction.y);player.x+=direction.x*210*dt;player.y+=direction.y*210*dt;if(input.dash){Object.assign(player,{state:'dash',time:0});sfx.dash()}else if(input.attack)startAttack()}input.attack=input.dash=false;player.x=Math.max(70,Math.min(1210,player.x));player.y=Math.max(65,Math.min(655,player.y));}
function startAttack(){Object.assign(player,{state:'attack',time:0,hit:new Set()});sfx.attack()}
function updateEnemies(dt){for(const enemy of enemies){enemy.facing=Math.atan2(player.y-enemy.y,player.x-enemy.x);enemy.cooldown-=dt;enemy.time+=dt;enemy.moving=false;const range=distance(player,enemy);if(enemy.state==='attack'){if(!enemy.hit&&enemy.time>.38&&enemy.time<.55&&range<100){if(damage(player,RULES.enemyDamage,player.state==='dash'||player.state==='hurt')){enemy.hit=true;Object.assign(player,{state:'hurt',time:0});sfx.hurt()}}if(enemy.time>.7)Object.assign(enemy,{state:'idle',time:0,cooldown:.65,hit:false})}else if(range<95&&enemy.cooldown<=0)Object.assign(enemy,{state:'attack',time:0,hit:false});else{const direction=normal(player.x-enemy.x,player.y-enemy.y);enemy.moving=true;enemy.x+=direction.x*(72+wave*2)*dt;enemy.y+=direction.y*(72+wave*2)*dt;}}}
function updateDrops(dt){for(const drop of drops){drop.time+=dt;if(distance(player,drop)<55){if(drop.type==='coin'){player.gold+=drop.amount;sfx.coin()}else{const healed=Math.min(drop.amount,player.maxHp-player.hp);player.hp+=healed;message=healed?`恢复 ${healed} 点生命`:'生命已满';sfx.heal()}drops.splice(drops.indexOf(drop),1)}}}
function updateParticles(dt){for(const p of particles){p.life-=dt;p.vy+=260*dt;p.x+=p.vx*dt;p.y+=p.vy*dt;p.vx*=.96}particles=particles.filter(p=>p.life>0)}
function update(dt){updatePlayer(dt);updateEnemies(dt);updateDrops(dt);updateParticles(dt);if(player.hp<=0){message='冒险失败 · 按 R 重试';sfx.defeat();return}if(!enemies.length){nextWave-=dt;if(nextWave<=0){spawnWave();nextWave=2}}}

function directionRow(angle){return(Math.round(angle/(Math.PI/4))+10)%8}
function drawActor(actor,image,duration){const row=directionRow(actor.facing),column=actor.state==='attack'?6+Math.min(5,Math.floor(actor.time/duration*6)):actor.moving?1+Math.floor(performance.now()/140)%4:0;ctx.imageSmoothingEnabled=false;ctx.drawImage(image,column*32,row*32,32,32,actor.x-40,actor.y-40,80,80)}
function bar(x,y,width,value,max,color){ctx.fillStyle='#080908dd';ctx.fillRect(x,y,width,18);ctx.fillStyle=color;ctx.fillRect(x+2,y+2,(width-4)*value/max,14)}
function draw(){ctx.imageSmoothingEnabled=false;for(let y=0;y<720;y+=64)for(let x=0;x<1280;x+=64)ctx.drawImage((x+y)%128?art.dirt:art.grass,x,y,64,64);for(const[x,y]of[[10,5],[1150,5],[10,585],[1150,585]])ctx.drawImage(art.tree,x,y,128,128);ctx.fillStyle='#06100a30';ctx.fillRect(0,0,1280,720);for(const drop of drops){const bob=Math.sin(drop.time*6)*5;ctx.fillStyle=drop.type==='coin'?'#ffd54d':'#52dc78';ctx.beginPath();ctx.arc(drop.x,drop.y+bob,drop.type==='coin'?9:11,0,7);ctx.fill();ctx.fillStyle='#fff9';ctx.fillRect(drop.x-2,drop.y+bob-6,4,12);if(drop.type==='heal')ctx.fillRect(drop.x-6,drop.y+bob-2,12,4)}for(const p of particles){ctx.globalAlpha=Math.max(0,p.life*1.7);ctx.fillStyle=p.color;ctx.fillRect(p.x,p.y,p.size,p.size)}ctx.globalAlpha=1;for(const enemy of enemies){drawActor(enemy,art[enemy.art],.7);bar(enemy.x-28,enemy.y-42,56,enemy.hp,enemy.maxHp,'#a43732')}if(player.hp)drawActor(player,art.hero,.24);bar(32,30,300,player.hp,player.maxHp,'#b43e3b');ctx.fillStyle='#f4d45a';ctx.font='bold 22px system-ui';ctx.textAlign='left';ctx.fillText(`金币  ${player.gold}`,35,78);ctx.fillStyle='#f0dfbd';ctx.textAlign='center';ctx.font='22px Georgia';ctx.fillText(message,640,54);ctx.font='16px system-ui';ctx.fillText(`第 ${wave} 波　剩余 ${enemies.length}`,640,82)}
function loop(now){const dt=Math.min((now-last)/1000,.033);last=now;if(player.hp>0)update(dt);else updateParticles(dt);draw();if(running)requestAnimationFrame(loop)}
reset();draw();
