import{RULES,spend,damage,regen}from'./combat.js';
const c=document.querySelector('canvas'),x=c.getContext('2d'),keys=new Set(),m={x:640,y:360,a:0,r:0};let run=0,last=0,msg='';
const p={x:250,y:360,hp:100,maxHp:100,stamina:100,maxStamina:100,state:'idle',t:0,face:0,hit:0};const e={x:930,y:360,hp:150,maxHp:150,state:'idle',t:0,face:3.14,hit:0,cd:1};
addEventListener('keydown',q=>{keys.add(q.code);if(q.code==='Space')m.a=1;if(q.code.startsWith('Shift'))m.r=1;if(q.code==='KeyR')reset()});addEventListener('keyup',q=>keys.delete(q.code));c.onmousemove=q=>{let b=c.getBoundingClientRect();m.x=(q.clientX-b.left)*1280/b.width;m.y=(q.clientY-b.top)*720/b.height};c.onmousedown=q=>q.button?m.r=1:m.a=1;c.oncontextmenu=q=>q.preventDefault();document.querySelector('button').onclick=()=>{document.querySelector('section').classList.add('hidden');run=1;last=performance.now();requestAnimationFrame(loop)};
const dist=()=>Math.hypot(p.x-e.x,p.y-e.y),norm=(a,b)=>{let l=Math.hypot(a,b)||1;return[a/l,b/l]};
function reset(){Object.assign(p,{x:250,y:360,hp:100,stamina:100,state:'idle',t:0});Object.assign(e,{x:930,y:360,hp:150,state:'idle',t:0,cd:1});msg='守墓人正在注视你'}
function update(dt){p.face=Math.atan2(m.y-p.y,m.x-p.x);p.t+=dt;if(p.state==='roll'){let[dX,dY]=norm((keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0),(keys.has('KeyS')?1:0)-(keys.has('KeyW')?1:0));p.x+=dX*430*dt;p.y+=dY*430*dt;if(p.t>.42)p.state='idle'}else if(p.state==='attack'){if(!p.hit&&p.t>.12&&p.t<.25&&dist()<90){damage(e,RULES.attackDamage);p.hit=1}if(p.t>.38)p.state='idle'}else{let[a,b]=norm((keys.has('KeyD')?1:0)-(keys.has('KeyA')?1:0),(keys.has('KeyS')?1:0)-(keys.has('KeyW')?1:0));p.x+=a*185*dt;p.y+=b*185*dt;if(m.r&&spend(p,RULES.rollCost))Object.assign(p,{state:'roll',t:0});else if(m.a&&spend(p,RULES.attackCost))Object.assign(p,{state:'attack',t:0,hit:0})}regen(p,dt,p.state!=='idle');m.a=m.r=0;p.x=Math.max(30,Math.min(1250,p.x));p.y=Math.max(50,Math.min(680,p.y));if(e.hp<=0){e.state='dead';msg='守墓人已倒下 · R 再战';return}e.face=Math.atan2(p.y-e.y,p.x-e.x);e.cd-=dt;e.t+=dt;if(e.state==='attack'){if(!e.hit&&e.t>.46&&e.t<.58&&dist()<105){damage(p,RULES.enemyDamage,p.state==='roll'&&p.t<.28);e.hit=1}if(e.t>.82)Object.assign(e,{state:'idle',t:0,cd:.6})}else if(dist()<650){if(dist()<92&&e.cd<0)Object.assign(e,{state:'attack',t:0,hit:0});else{let[a,b]=norm(p.x-e.x,p.y-e.y);e.x+=a*105*dt;e.y+=b*105*dt}}if(p.hp<=0)msg='你已陨落 · 按 R 重试'}
function bar(a,b,w,v,max,col){x.fillStyle='#090909';x.fillRect(a,b,w,16);x.fillStyle=col;x.fillRect(a+2,b+2,(w-4)*v/max,12)}function actor(o,col,r){x.save();x.translate(o.x,o.y);x.rotate(o.face+(o.state==='attack'?o.t*3-1:0));x.fillStyle=col;x.beginPath();x.arc(0,0,r,0,7);x.fill();x.fillStyle='#ddd';x.fillRect(r,-3,40,6);x.restore()}
function draw(){let g=x.createRadialGradient(640,360,20,640,360,700);g.addColorStop(0,'#293229');g.addColorStop(1,'#0c100e');x.fillStyle=g;x.fillRect(0,0,1280,720);x.fillStyle='#d0672d';x.beginPath();x.arc(150,360,25,0,7);x.fill();if(e.state!=='dead')actor(e,e.state==='attack'&&e.t<.46?'#d28a4c':'#803c36',28);if(p.hp)actor(p,p.state==='roll'&&p.t<.28?'#d5eee5':'#719b8c',19);bar(35,35,300,p.hp,100,'#963936');bar(35,58,250,p.stamina,100,'#6d9656');if(e.hp>0){bar(370,665,540,e.hp,150,'#853431');x.textAlign='center';x.fillStyle='#ddd';x.fillText('荒原守墓人',640,650)}x.font='24px Georgia';x.textAlign='center';x.fillStyle='#e4d6bc';x.fillText(msg,640,110)}function loop(n){let dt=Math.min((n-last)/1000,.033);last=n;if(p.hp&&e.hp)update(dt);draw();requestAnimationFrame(loop)}reset();draw();
